version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    driver: bridge

volumes:
  mysql-db-storage:

services:
  mysql-db:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root@123
    ports:
      - 3306:3306
    networks:
      - web-app-net
    volumes:
      - mysql-db-storage:/var/lib/mysql
      # Note: Place the db_dump.sql in the mysql-dump dir, 
      # which should be in the same dir as the docker-compose.yaml file.
      #- ./mysql-dump:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
#    links:
#      - 'mysql-db:db'
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_PMADB: wordpress
      MYSQL_ROOT_PASSWORD: root@123
    ports:
      - 8081:80
    networks:
      - web-app-net
    depends_on:
      - mysq-db
    restart: on-failure

  wordpress-site:
    image: wordpress:latest
#    links:
#      - 'mysql-db:mysql'
    environment:
      WORDPRESS_DB_HOST: mysql-db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root@123
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    networks:
      - web-app-net
    depends_on:
      - mysql-db
    restart: on-failure

#end of scripts
